export type {
  Lawyer,
  LegalCase,
  LawyerStatus,
  Specialization,
  CaseStatus,
  CaseOutcome,
  Currency,
  CaseType,
  LawyerTabType,
  MoneyAmount,
  TimelineEvent,
  DocumentComment,
  CaseDocument,
  CaseNote,
  CaseNoteAttachment,
  ThirdParty,
  Court,
  Judge,
  CaseFilters,
  LawyerFilters,
  RecoveredItem,
  ExpenseItem,
  CaseRecordUpdate,
  CaseUpdateType,
} from "./lawyer.types";

export type {
  GetLawyersResponse,
  GetLawyerResponse,
  GetCasesResponse,
  GetCaseResponse,
  CreateLawyerRequest,
  UpdateLawyerRequest,
  CreateCaseRequest,
  UpdateCaseRequest,
} from "./api.types";
